#! /bin/sh
# Start Autopilot installer. Fully installs a complete working environment from a fresh install.
set -e

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

echo "#█▓▒░"
echo "#█▓▒░"
echo "#█▓▒░		Autopilot "
echo "#█▓▒░"
echo "#█▓▒░"


while true
do
 read -r -p "#█▓▒░ Type "BEGIN" to start the installation: " input

 case $input in
     [B][E][G][I][N])

# Refresh and upgrade pacman packages
echo -e "\n#█▓▒░	Refreshing pacman and upgrading packages "
sudo pacman -S yay --noconfirm --needed
yay -Syyu
echo -e "#█▓▒░	DONE \n "

# Insatll system tools
echo -e "#█▓▒░	Installing system tools: "
yay -S arandr base-devel gtop htop stow pavucontrol picom-ibhagwan-git redshift gparted scrot intel-undervolt cpupower-gui xorg-xinput cpupower gparted rxvt-unicode-patched tlp tlpui-git linux-latest-tp_smapi xclip xdo-git xorg-xsetroot --noconfirm --needed
echo -e "#█▓▒░	DONE \n"

# Stow Dotfiles
echo -e "\n#█▓▒░	Stowing dotfiles "
cd ~/dots
stow bspwm picom polybar rofi scripts sxhkd wpg X
cd ~
echo -e "#█▓▒░	DONE \n"

# Install text editors
echo -e "\n#█▓▒░	Installing editors: "
#yay -S atom micro --noconfirm
echo -e "#█▓▒░	DONE \n"

# Install browsers
echo -e "#█▓▒░	Installing browsers:  "
#yay -S firefox-nightly w3m tor-browser --noconfirm
yay -S firefox-nightly --noconfirm --needed
echo -e "#█▓▒░	DONE \n"

# Install media
echo -e "#█▓▒░	Installing media: "
yay -S feh dropbox spotify playerctl --noconfirm --needed
echo -e "#█▓▒░	DONE \n"

# Install rice
echo -e "#█▓▒░	Installing rice: "
yay -S bspwm-git betterlockscreen sxhkd-git wpgtk-git lxappearance rofi-git polybar-git --noconfirm --needed
echo -e "#█▓▒░	DONE \n"

# Install extras
#echo -e "#█▓▒░	Installing extras: "
#yay -S tor-browser --noconfirm
#echo -e "#█▓▒░	DONE \n"

#echo -e "\n#█▓▒░	Changing default shell "
#chsh -s /bin/zsh
#sudo chsh -s /bin/zsh
#echo -e "#█▓▒░	DONE \n"

# Make wpg install gtk & bspwm templates
echo -e "\n#█▓▒░	Setting wpg themes "
wpg-install.sh -g -b -r
echo -e "#█▓▒░	DONE \n"

# Install extras
#echo -e "#█▓▒░	Installing extras: "
yay -S zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting flameshot --noconfirm --needed
#echo -e "#█▓▒░	DONE \n"

# Install fonts
echo -e "#█▓▒░	Installing fonts: "
yay -S otf-sfmono lohit-fonts ttf-font-awesome --noconfirm --needed
echo -e "#█▓▒░	DONE \n"

echo -e "\n#█▓▒░	Removing and Linking some config files "
sudo rm /etc/intel-undervolt.conf
sudo rm /etc/tlp.conf

sudo ln -s /home/craig/scripts/autopilotfiles/intel-undervolt.conf /etc/intel-undervolt.conf
sudo ln -s /home/craig/scripts/autopilotfiles/tlp.conf /etc/tlp.conf
echo -e "#█▓▒░	DONE \n"
clear

echo -e "\n#█▓▒░	Starting and enabling systemctl services "
sudo intel-undervolt apply
sudo systemctl enable tlp.service intel-undervolt.service
sudo systemctl start tlp.service intel-undervolt.service
#betterlockscreen@$USER
 ;;

 	[qQ])
exit
 ;;
     *)
 echo "Try that one again."
 ;;
 esac
done
