#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
instance=$3;
class=$2;

case $class in
	(Gimp*) echo follow=on;;
	(Spotify) echo desktop=^5;;
	(Signal) echo desktop=^2;;
	('')
		case $(ps -p "$(xdo pid $id)" -o comm= 2>/dev/null) in
			(spotify) echo desktop=^5;;
		esac;;
esac;

# vim: set ft=sh :
