#!/usr/bin/env bash
set -euo pipefail

color=$(gpick -so 2>/dev/null)

if [ -n "$color" ]; then
    dunstify -i ~/.config/dunst/images/color-dropper.png -a ColorPicker -u normal "$color" &&
    echo $color | xclip -selection c
fi
