#! /bin/sh
pacman -S --needed - < /home/craig/Dropbox/Stuff/dots/pkglist.txt


yay -S bspwm-git
yay -S google-chrome-dev
yay -S i3lock-color-git
yay -S lohit-fonts
yay -S ly-git
yay -S nerd-fonts-complete
yay -S networkmanager-dmenu-git
yay -S otf-sfmono
yay -S polybar-git
yay -S pulseeffects-git
yay -S rofi-dmenu
yay -S rofi-git
yay -S runelite-launcher
yay -S rxvt-unicode-patched
yay -S signal
yay -S spotify
yay -S sxhkd-git
yay -S tor-browser-en
yay -S wpgtk-git
