#!/bin/bash
source "$HOME/.cache/wal/colors.sh"
i3lock --force-clock -e -B=8 --composite --indpos="x+50:h-50" --timepos="x+210:h-35" --insidecolor="$color1"ff --ringcolor="$color1"ff --line-uses-inside --keyhlcolor="$color0"ff --bshlcolor=$color0"ff" --insidevercolor="$color1"ff --ringvercolor="$color1"ff --ringwrongcolor="$color0"ff --insidewrongcolor="$color0"ff --radius=25 --ring-width=5 --noinputtext=" " --veriftext=" " --verifcolor="$color7"ff --wrongtext=" " --wrongcolor="$color0"ff --timestr="%-I:%M:%S" --datestr=" " --timecolor="$color7"ff --timesize=45
