#! /bin/sh
#█▓▒░  monitor setting
#xrandr --output LVDS-0 --auto --rotate normal --pos 0x0 --output DP-0 --auto --rotate normal --left-of LVDS-0 --output VGA-0 --right-of LVDS-0 &
bash "$HOME/scripts/disp" &

#█▓▒░
#█▓▒░ relaunch programs

#quickserve .cache/wal/ &&
sxhkd &
dropbox &
dcompmgr --gl &
bash "$HOME/scripts/mouse" &
bash "$HOME/scripts/bars" &

pulseeffects --gapplication-service &

#█▓▒░
#█▓▒░ randomly set theme on load
#wpg -m &
#. "${HOME}/.config/wpg/formats/colors.sh" &

#█▓▒░
#█▓▒░ bspwm settings // ० ० ० ० ०

bspc monitor DP-2 -d एक दो तीन चार पांच
bspc monitor HDMI-0 -d ० ० ० ० ०

bspc config border_width         4
bspc config window_gap           25
#bspc config border_radius        15

bspc config split_ratio          0.50
bspc config top_padding          90
bspc config bottom_padding       25
bspc config left_padding         25
bspc config right_padding        25
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


wpg -m &
. "${HOME}/.config/wpg/formats/colors.sh" &


bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color0"

#█▓▒░  bspwm set Authy Chrome app to floating
bspc rule -a *:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb state=floating
