#! /bin/sh
#█▓▒░  monitor setting
#xrandr --output LVDS-0 --auto --rotate normal --pos 0x0 --output DP-0 --auto --rotate normal --left-of LVDS-0 --output VGA-0 --right-of LVDS-0 &

#█▓▒░ relaunch programs
wpg -m &
sxhkd &
dropbox
bash "$HOME/scripts/mouse" &
bash "$HOME/scripts/bars" &

#█▓▒░  set cursor theme
xsetroot -cursor_name left_ptr

#█▓▒░ bspwm settings // ० ० ० ० ०
bspc monitor DP-2 -d एक दो तीन चार पांच
bspc monitor HDMI-0 -d ० ० ० ० ०
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config border_width         4
bspc config window_gap           15
bspc config top_padding          45
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#█▓▒░ set bspwm border colors from wpgtk
bash /home/craig/.config/bspwm/bspwm_colors.sh &
