#!/usr/bin/env zsh

notify-send -i ~/.config/dunst/images/yoga.png "Health" "Fix your posture! <br><br>You don't want to end up crooked, do you?" && mpv ~/.config/dunst/sounds/Breeze.mp3 &> /dev/null
