--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/craig/.config/wpg/wallpapers/Sacred.jpg"

-- Special
background="#0d1215"
foreground="#fffbfa"
cursor="#fffbfa"

-- Colors
color0="#0d1215"
color1="#BB6048"
color2="#6199A7"
color3="#D88C71"
color4="#477A85"
color5="#966057"
color6="#60A1B1"
color7="#cfc9c8"
color8="#0d1215"
color9="#ff724c"
color10="#6cd1ea"
color11="#ffab7d"
color12="#4fa7ba"
color13="#d27161"
color14="#6bdcf7"
color15="#fffbfa"
