--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/craig/.config/wpg/wallpapers/Tulip.jpg"

-- Special
background="#0d1215"
foreground="#d5ffff"
cursor="#d5ffff"

-- Colors
color0="#0d1215"
color1="#D06B1A"
color2="#464D40"
color3="#D99837"
color4="#973124"
color5="#B26151"
color6="#A4571D"
color7="#9fc2c2"
color8="#0d1215"
color9="#ff8912"
color10="#5a6d4a"
color11="#ffc935"
color12="#d03622"
color13="#f87258"
color14="#e16f19"
color15="#d5ffff"
