# Shell variables
# Generated by 'wal'
wallpaper='/home/craig/.config/wpg/wallpapers/Sacred.jpg'

# Special
background='#0d1215'
foreground='#fffbfa'
cursor='#fffbfa'

# Colors
color0='#0d1215'
color1='#BB6048'
color2='#6199A7'
color3='#D88C71'
color4='#477A85'
color5='#966057'
color6='#60A1B1'
color7='#cfc9c8'
color8='#0d1215'
color9='#ff724c'
color10='#6cd1ea'
color11='#ffab7d'
color12='#4fa7ba'
color13='#d27161'
color14='#6bdcf7'
color15='#fffbfa'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
